# SPDX-FileCopyrightText: © 2026 Julian Andrews
# SPDX-License-Identifier: MIT

[package]
name = "rwm"
description = "Tiny scrolling window manager for river"
license = "MIT"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.11.0"
serde = { version = "1", features = ["derive"] }
toml = "0.9"
wayland-backend = "0.3.14"
wayland-client = "0.31.13"
wayland-scanner = "0.31.9"
libc = "0.2"
xkbcommon = "0.9"
